version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: jshimko/meteor-launchpad:latest
    environment:
      - METEOR_ALLOW_SUPERUSER: true
    steps:
      - checkout
      # - restore_cache:
      #     key: meteor-release-cache-{{ checksum ".meteor/release" }}
      # - restore_cache:
      #     key: meteor-packages-cache-{{ checksum ".meteor/versions" }}
      # - restore_cache:
      #     key: npm-packages-cache-{{ checksum "package.json" }}
      # - run:
      #     name: install meteor
      #     command: |
      #       apt-get update
      #       apt-get install -y curl
      #       curl https://install.meteor.com/ | sh
      - run:
          name: check versions
          command: |
            echo "Meteor version:"
            meteor --version
            echo "Meteor node version:"
            meteor node -v
            echo "Meteor npm version:"
            meteor npm -v
      - run: 
          name: install npm dependencies
          command: meteor npm i
      - run:
          name: code linting
          command: |
            echo "Installing semistandard deps manually (hacky fix)"
            cd node_modules/semistandard
            meteor npm i
            cd ../../
            meteor npm run lint
      - run:
          name: unit tests
          command: meteor npm run test:unit
      - save_cache:
          key: npm-packages-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules/
      - save_cache:
          key: meteor-packages-cache-{{ checksum ".meteor/versions" }}
          paths:
            - ./meteor
      - save_cache:
          key: meteor-release-cache-{{ checksum ".meteor/release" }}
          paths:
            - ~/.meteor
      - store_artifacts:
          path: ./tests/coverage/unit-tests/
          destination: unit-tests
  e2e_tests:
    working_directory: ~/app
    docker:
      - image: jshimko/meteor-launchpad:latest
    environment:
      - METEOR_ALLOW_SUPERUSER: true
    steps:
      - checkout
      - restore_cache:
          key: meteor-release-cache-{{ checksum ".meteor/release" }}
      - restore_cache:
          key: meteor-packages-cache-{{ checksum ".meteor/versions" }}
      - restore_cache:
          key: npm-packages-cache-{{ checksum "package.json" }}
      - run:
          name: start app in background
          command: meteor npm run start
          background: true
      - run:
          name: wait for app to start
          command: sleep 2m
      - run:
          name: e2e tests
          command: meteor npm run test:e2e
          no_output_timeout: 2m
workflows:
  version: 2
  build-and-e2e-tests:
    jobs:
      - build
      - e2e_tests:
          requires:
            - build