version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: tozd/meteor:ubuntu-xenial
    environment:
      - METEOR_ALLOW_SUPERUSER: true
    steps:
      - checkout
      - run:
          name: check versions
          command: |
            meteor --version
            meteor node -v
            meteor npm -v
      - run: 
          name: install npm dependencies
          command: meteor npm i
      - run:
          name: code linting
          command: meteor npm run lint
      - run:
          name: unit tests
          command: meteor npm run test:unit