version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: tozd/meteor:ubuntu-xenial
    steps:
      - checkout
      - run: 
        name: npm install
        command: meteor npm i
      - run:
        name: code lintint
        command: meteor npm run lint
      - run:
        name: unit tests
        command: meteor npm run test:unit