version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: tzapu/development-meteor:latest
    environment:
      - METEOR_ALLOW_SUPERUSER: true
    steps:
      - checkout
      - restore_cache:
          key: meteor-release-{{ checksum ".meteor/release" }}
      - restore_cache:
          key: meteor-packages-{{ checksum ".meteor/versions" }}
      - restore_cache:
          key: npm-packages-{{ checksum "package.json" }}
      - run:
          name: fix inotify file watchter for Meteor
          command: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - run:
          name: check versions
          command: |
            echo "Meteor version:"
            meteor --version
            echo "Meteor node version:"
            meteor node -v
            echo "Meteor npm version:"
            meteor npm -v
      - run: 
          name: install npm dependencies
          command: meteor npm i
      - run:
          name: code linting
          command: |
            echo "Installing semistandard deps manually (hacky fix)"
            cd node_modules/semistandard
            meteor npm i
            cd ../../
            meteor npm run lint
      - run:
          name: unit tests
          command: meteor npm run test:unit
      - save_cache:
          key: meteor-release-{{ checksum ".meteor/release" }}
          paths:
            - ~/.meteor
      - save_cache:
          key: meteor-packages-{{ checksum ".meteor/versions" }}
          paths:
            - .meteor/
      - save_cache:
          key: npm-packages-{{ checksum "package.json" }}
          paths:
            - ./node_modules/
            - ~/.npm/
      - store_artifacts:
          path: ./tests/coverage/unit-tests/
          destination: unit-tests
  e2e_tests:
    working_directory: ~/app
    docker:
      - image: tzapu/development-meteor:latest
    environment:
      - METEOR_ALLOW_SUPERUSER: true
    steps:
      - checkout
      - restore_cache:
          key: meteor-release-{{ checksum ".meteor/release" }}
      - restore_cache:
          key: meteor-packages-{{ checksum ".meteor/versions" }}
      - restore_cache:
          key: npm-packages-{{ checksum "package.json" }}
      - run:
          name: fix inotify file watchter for Meteor
          command: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - run: 
          name: install npm dependencies
          command: meteor npm i
      - run:
          name: starting app and running e2e tests
          command: meteor npm run test:e2e-standalone
          no_output_timeout: 2m
workflows:
  version: 2
  build-and-e2e-tests:
    jobs:
      - build
      - e2e_tests:
          requires:
            - build